{% if version[1]|int >= 10  %}
apiVersion: serving.knative.dev/v1 # Current version of Knative
{% else %}
apiVersion: serving.knative.dev/v1alpha1
{% endif %}
kind: Service
metadata:
  name: {{ app_name }}-service # The name of the app
  namespace: {{env}} # The namespace the app will use
spec:
  template:
    spec:
      containers:
      - image: {{ docker_artifactory_repo_url }}/{{ app_docker_image }}:{{ docker_tag }} # The URL to the image of the app
