apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ app_name }}-virtualservice
  namespace: {{env}}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  # Set host to the domain name that you own.
  hosts:
  - {{ domain }}
  http:
  - match:
    - uri:
        prefix: "{{ app_url }}"
    rewrite:
      # Rewrite the original host header to the host header of Search service
      # in order to redirect requests to Search service.
      authority: {{ app_name }}-service.{{env}}.{{ domain }}
    route:
      # knative-ingressgateway is the k8s service created by Knative as the
      # shared gateway of all traffic incoming to the cluster.
      # Basically here we redirect the request to the cluster entry again with
      # updated header "search-service.default.example.com" so the request will
      # eventually be directed to Search service.
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
        weight: 100
